# ???????????? application.properties ?
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:calorie_calculator}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

# ????????????
mybatis.configuration.map-underscore-to-camel-case=true

server.port=${PORT:8080}